In [ ]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)

In [1]:
#1. Answer
import pandas as pd
data = {'Feature1': ['10', '20', 'Thirty'], 
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')

print(df)

   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [ ]:
#2. Question
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)  # Error: fillna() does not modify in place

print(df)

In [2]:
#2. Answer

import pandas as pd

data = {'A': [1, 2, None],
        'B': [4, None, 6]}

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(df.mean(), inplace=True) 

print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

In [3]:
#3. Answer

from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
#4. Question
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], 20, 30, 40, 50])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


In [4]:
#4. Answer

from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5. Question
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)


In [5]:
#5. Answer

from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

model = LogisticRegression()
model.fit(X, y)


LogisticRegression()

In [ ]:
#6. Question
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'])  # Error: Data should be reshaped
print(encoded)


In [6]:
#6. Answer

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])


print(encoded.toarray())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#7. Question
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
#7. Answer

from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("X_train:", X_train)
print("y_train:", y_train)

X_train: [[5, 6], [1, 2]]
y_train: [0, 0]


In [ ]:
#8. Question
from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train)


In [8]:
#8. Answer

from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoded = encoder.fit_transform(y_train)

model = LogisticRegression()
model.fit(X_train, y_train)

print(model.predict([[4,5]]))

['yes']


In [ ]:
#9. Question
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

model = LinearRegression()
model.fit(X_train, y_train)  


In [9]:
#9. Answer

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

X_train = np.array([[1, 2], [3, np.nan], [5, 6]]) # Creating a dataset with missing values.
y_train = np.array([10, 20, 30])

from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(strategy="mean") # Replace NaN with the mean.

X_train_fixed = imputer.fit_transform(X_train) 

model = LinearRegression() # Train the model
model.fit(X_train_fixed, y_train) 

prediction = model.predict([[1, 2]]) # Make the prediction
print("Predicted Output:", prediction)

Predicted Output: [10.]


In [ ]:
#10. Question
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

In [10]:
# 10. Answer
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

model = DecisionTreeClassifier()
model.fit(X_train, y_train_encoded)

prediction = model.predict([[5, 6]]) # Make the prediction
print("Predicted Output:", prediction)

Predicted Output: [1]


In [ ]:
#11. Question
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


In [11]:
#11.Answer

from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

from sklearn.preprocessing import StandardScaler #Feature scaling using StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model = SVC()
model.fit(X_train_scaled, y_train)

X_test_scaled = scaler.transform([[1, 150]])
print(model.predict(X_test_scaled)) 


[0]
